// Generated by VerilogCanvas. Verilog-2001.
// Child module implementations must be supplied separately.
module branch_demo (
    input wire [7:0] data
);



my_module u_b (
    .a(data)
);

my_module u_c (
    .a(data)
);

endmodule
