// Generated by VerilogCanvas. Verilog-2001.
// Child module implementations must be supplied separately.
module demo_top (
    input wire clk,
    input wire rst_n,
    input wire [7:0] data_in,
    output wire [7:0] data_out,
    output wire [7:0] monitor
);


assign monitor = data_out;

data_pipe #(
    .WIDTH(8)
) u_pipe (
    .clk(clk),
    .rst_n(rst_n),
    .data_in(data_in),
    .data_out(data_out)
);

endmodule
