// Generated by VerilogCanvas. SystemVerilog.
// Child module implementations must be supplied separately.
module demo_sv_top (
    input logic clk,
    input logic rst_n,
    input logic signed [1:0][7:0] data_in,
    output logic signed [1:0][7:0] data_out
);



sv_pipeline #(
    .WIDTH(8),
    .LANES(2),
    .LABEL("pipeline")
) u_sv_pipeline (
    .clk(clk),
    .rst_n(rst_n),
    .data_in(data_in),
    .data_out(data_out)
);

endmodule
