// Generated by VerilogCanvas. Verilog-2001.
// Child module implementations must be supplied separately.
module group_demo (
);



// ############ PROCESSING #############
wire [7:0] syn_net_0;

source u_a (
    .y(syn_net_0)
);

sink u_b (
    .a(syn_net_0)
);

source u_outside (
    .y()
);

endmodule
