// Generated by VerilogCanvas. SystemVerilog.
// Child module implementations must be supplied separately.
module top (
    input logic [1:0] modulation,
    input logic enable,
    output logic mode
);

typedef enum logic [1:0] { MOD_AM = 0, MOD_FM = 1 } modulation_t;



// Inline HDL: mode_control
// Prototype mode decoding; MOD_AM is declared in the top level.




assign mode = enable && (modulation == MOD_AM);

endmodule
