// Generated by VerilogCanvas. SystemVerilog.
// Child module implementations must be supplied separately.
module label_demo_top (
    input logic clk,
    input logic rst_n,
    input logic signed [1:0][7:0] data_in,
    output logic signed [1:0][7:0] data_out
);

logic sys_clk;
logic reset_n;
logic signed [1:0][7:0] sample_bus;
logic signed [1:0][7:0] result_bus;

assign sys_clk = clk;
assign reset_n = rst_n;
assign sample_bus = data_in;
assign data_out = result_bus;

sv_pipeline #(
    .WIDTH(8),
    .LANES(2),
    .LABEL("pipeline")
) u_sv_pipeline (
    .clk(sys_clk),
    .rst_n(reset_n),
    .data_in(sample_bus),
    .data_out(result_bus)
);

endmodule
