// Generated by VerilogCanvas. SystemVerilog.
// Child module implementations must be supplied separately.
module transform_demo_top (
    input logic [2:0] modulation
);

typedef enum logic [2:0] {MOD_AM = 3'd0, MOD_FM = 3'd1} modulation_t;



agc inst_agc (
    .mode((modulation == MOD_AM) ? 1'b1 : 1'b0)
);

endmodule
